Vidly/ViewModels/MoviesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Vidly.Models;

namespace Vidly.ViewModels
{
    public class MoviesViewModel
    {
        public List<Movie> Movies { get; set; }
    }
}

Vidly/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Vidly.Models;
using Vidly.ViewModels;
using System.Data.Entity;

namespace Vidly.Controllers
{
    public class MoviesController : Controller
    {
        private ApplicationDbContext _context;

        public MoviesController()
        {
            _context = new ApplicationDbContext();
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }
       
        public ActionResult Index()
        {
            var movies = _context.Movies.Include(m => m.Genre).ToList();
            return View(movies);
        }

        public ActionResult Details(int id)
        {// Kas yra singleOrDefault?
            var movie = _context.Movies.Include(m => m.Genre).SingleOrDefault(m => m.Id == id);
            
            if (movie == null)
                return HttpNotFound();
            
            return View(movie);
            
        }
        public ActionResult Random()
        {
            // Define movie variable using Movie Model
            var movie = new Movie() { Name = "Shrek!" };
            // Pass movie var to View
            return View(movie);
        }
    }
}

Vidly/Views/Movies/Details.cshtml
@model Vidly.Models.Movie
@{
    ViewBag.Title = Model.Name;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>
<ul>
    <li>Genre: @Model.Genre.Name </li>
    <li>Release date: @Model.ReleaseDay.ToLongDateString() </li>
    <li>Date added: @Model.DateAdded.ToLongDateString() </li>
    <li>Number in stock: @Model.NumberInStock</li>
</ul>

Vidly/Views/Movies/Index.cshtml
@model IEnumerable<Vidly.Models.Movie>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movies</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th>Movie</th>
            <th>Genre</th>
        </tr>
    </thead>

    @foreach (var movie in Model)
    {
    <tr>
        <td>@Html.ActionLink(movie.Name, "Details", "Movies", new { id = movie.Id }, null)</td>
        <td>@movie.Genre.Name</td>
    </tr>
    }

</table>

Vidly/Views/Movies/NoSuchMovie.cshtml
@{
    ViewBag.Title = "NoSuchMovie";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Movie not found!</h2>

Vidly/Views/Movies/Random.cshtml
@* Use a directive to specify type of a model*@
@model Vidly.Models.Movie
@{
    ViewBag.Title = "Random";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Model.Name</h2>